codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 65%

flag_management:
  individual_flags:
    - name: backend
      paths:
        - src/main/java/
      carryforward: true
    - name: frontend
      paths:
        - src/main/frontend/
      carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
